languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Skitii"
  logo = "/img/octopus.png"

dateFormat = "2 January 2006"

[author]
  name = "Skitii"
  image = "/img/donatello.png"